FROM node:lts
WORKDIR /usr/src/app
# COPY package*.json ./
# RUN npm ci
# COPY . .
# RUN npm run build
# включаем инспектор для дебага
# CMD ["node", "--inspect=0.0.0.0:9229", "dist/main.js"]
CMD ["sleep", "infinity"]
